apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullname }}
  labels:
    app: {{ .Values.labelType }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
        name: {{ .Values.fullname }}
  template:
    metadata:
      labels:
        name: {{ .Values.fullname }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP