apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.labelType }}
