name: "CI Workflow"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, edited, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["18.x", "20.x"]
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.version}}
          cache-dependency-path: "package-lock.json"
          check-latest: true

      - name: Install the dependencies
        run: npm ci

      - name: Lint the Code
        run: npm lint

  # dockernize:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout the Code
  #       uses: actions/checkout@v4
